# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR ./

# Copy package.json and package-lock.json to the working directory
# COPY package*.json ./

# Install app dependencies
# RUN npm install



# Expose port 8800 to the outside world
EXPOSE 8800


# Command to run the application
CMD node index.js
