import type { Metadata } from "next";
import "../../styles/globals.css";
import Navbar from "@/src/components/Navbar";
import Layout from "@/src/components/Layout";
import SidebarWithBurgerMenu from "@/src/components/Sidebar";

export const metadata: Metadata = {
  title: "RDPlanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // if (typeof window !== "undefined") {
  return (
    <html lang="en">
      <body>
        <Layout>
          <Navbar />
          <div className="absolute">
             <SidebarWithBurgerMenu/>
          </div>
          {children}
        </Layout>
      </body>
    </html>
  );}
// }
